name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0
    - name: docker login
      env :
        DOCKER_USER : ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
      run : |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bangarsanju12/cams_parser
    - name: docker push
      run: docker push bangarsanju12/cams_parser:latest
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: root
        port: 22
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "docker-compose.yml"
        target: /root

      
    # - name: Install sshpass
    #   run: sudo apt-get install -y sshpass
    # - name: Copy docker-compose.yml to VPS
    #   run: |
    #     sshpass -p "${{ secrets.PASSPHRASE }}" scp -o StrictHostKeyChecking=no ./docker-compose.yml root@82.180.147.48:/root

    # - name: Run Docker Compose on VPS
    #   run: |
    #     sshpass -p "${{ secrets.PASSPHRASE }}" ssh -o StrictHostKeyChecking=no user@${{ secrets.HOST }} 'cd /path/to/your/app && docker-compose down && docker-compose up -d --build'

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: 22
        script: |
          cd ~
          ls
          docker pull bangarsanju12/cams_parser:latest
          cd /root && docker compose down --rmi all && 
          docker compose up -d
          
    # - name: Copy files to VPS
    #   run: |
    #     scp -o StrictHostKeyChecking=no -r ./* root@${{ secrets.HOST }}:/root/
          
